name: MundoFacil
description: Mundo Facil APP

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  splashscreen: ^1.2.0
  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/favicon.png"

flutter:

  uses-material-design: true

  assets:
    
    - assets/